# Generated by Django 3.0.7 on 2020-06-14 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dm', models.TextField(default='Hey')),
                ('un', models.TextField()),
            ],
        ),
    ]
